version: "3"
services:
  web:
    image: com.service/user-management:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.3"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  visualizer:
      image: dockersamples/visualizer:stable
      ports:
        - "8900:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        placement:
          constraints: [node.role == manager]
      networks:
        - webnet
networks:
  webnet: