version: "3"
services:
  user-management-service:
    image: user-management:latest
    depends_on:
      - mysql_database
    restart: on-failure
    ports:
      - 8080:8080
    links:
      - mysql_database:mysql
    environment:
      - DB_URL=mysql:3306
      - DB_NAME=user_management_database
      - DB_USERNAME=root
      - DB_PASSWORD=1111
      - FAKE_DATA=true

  mysql_database:
    image: mysql:5.6.39
    restart: on-failure
    ports:
      - 3308:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1111
      - MYSQL_DATABASE=user_management_database

volumes:
  mysql_data:
