version: "3"
services:
  service-discovery:
    image: consul:latest
    restart: on-failure
    ports:
      - 8500:8500

  service1:
    image: user-management:latest
    depends_on:
      - service-discovery
    restart: on-failure
    ports:
      - 3000:8080
    links:
      - mysql_database:mysql
      - service-discovery:consul
    environment:
      - DB_URL=mysql:3308
      - DB_NAME=user_management_database
      - DB_USERNAME=root
      - DB_PASSWORD=Worksvn
      - FAKE_DATA=true
      - CONSUL_HOST=consul \
      - CONSUL_PORT=8500

  service2:
    image: user-management:latest
    depends_on:
      - service-discovery
    restart: on-failure
    ports:
      - 3001:8080
    links:
      - mysql_database:mysql
      - service-discovery:consul
    environment:
      - DB_URL=mysql:3308
      - DB_NAME=user_management_database
      - DB_USERNAME=root
      - DB_PASSWORD=Worksvn
      - FAKE_DATA=true
      - CONSUL_HOST=consul \
      - CONSUL_PORT=8500

#  mysql_database:
#    image: mysql:5.6.39
#    restart: on-failure
#    ports:
#      - 3308:3306
#    volumes:
#      - mysql_data:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=1111
#      - MYSQL_DATABASE=user_management_database

#volumes:
#  mysql_data: