spring:
  application:
    name: user-management-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${server.port}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s

server:
  port: 8080

management:
  sercurity:
    enabled: false



